### ISSUE TITLE
[dgus-display] Numerical input works incorrectly

### ISSUE THREAD

**Issue by thghca** [Desuuuu/klipper#133]
I tried move z to 0.15. I can type 0.1 but when i press 5 it become 01.5

**Comment by Thinkersbluff** [comment]
I suspect the divide by 10 performed in vars-in.cfg for each of [t5uid1_var __move_x], [t5uid1_var __move_y] and [t5uid1_var __move_z] is causing this error.  I changed 10 to 1 and it solved my problem.

**Comment by Desuuuu** [comment]
The numpad behaviour is handled by the touchscreen's firmware itself. Going past the configured number of decimals shifts everything to the left and this is not configurable AFAIK.
