### ISSUE TITLE
Please add support for M112 Emergency Shutdown from the UI

### ISSUE THREAD

**Issue by Thinkersbluff** [Desuuuu/klipper#137]
For safety, there should be an Emergency Stop button on every screen, which triggers an immediate M112 shutdown.

Is there a way to command M112 from the UI?

**Comment by Thinkersbluff** [comment]
Update: I found how this is done, and added this new "variable" to the vars_in.cfg file in my fork:

[t5uid1_var __M112]
type: input
address: 0x2FFF
data_type: uint16
script:
  M112
run_as_gcode: true

Question: Is there a protocol for coordinating on the allocation of new variable addresses?

**Comment by Desuuuu** [comment]
There isn't, you simply pick an address and use the same on each side.

Regarding your issue, I have no plan to continue working on the older version of the firmware.

**Comment by Thinkersbluff** [comment]
Thanks for getting back to me!
A friend with python skills decoded the design for me, enough for me to learn how to create buttons that call Klipper macros, so I was able to solve my own problem, as you say.

Question: When you say "older version of the firmware", are you referring to the static DWIN_SET UI or to this Klipper firmware ? 

-  I had to create my own version of the DWIN_SET, for the CR6 T5L displays, so no problem, there.
- Are you also saying that you don't plan to continue maintaining the dgus-reloaded directory and files?

**Comment by Desuuuu** [comment]
By older version, I mean the `dgus-reloaded` one.

**Comment by Thinkersbluff** [comment]
Oh. That's a shame.

I just started working with DGUS-reloaded.  Although my python "skills" are near non-existent, I find your software architecture to be very elegant and easy to learn. 

Thank you again, for this wonderful "leg-up."

I do have a couple of friends I hope can help me troubleshoot the other issues I posted, here.  We would like to continue to develop and stabilize our CR6 variant.


Questions: 
- Are all of your DGUS-reloaded Klipper customizations contained within the ~/klipper/klippy/extras/t5uid1 folder? 

- In particular, whatever you modified to tailor the make menuconfig function for DGUS-reloaded is obviously also a critical part of this firmware.  
Are those mods elsewhere in the ~/klipper tree? 

- Do you plan to continue developing the dynamic display solution, here, or have you now "moved-on" from this project?

**Comment by Desuuuu** [comment]
You can view the modifications by comparing the branches: https://github.com/Klipper3d/klipper/compare/master...Desuuuu:klipper:dgus-reloaded

I would like to finish the new implementation at some point. No promise on when it might happen though.

**Comment by Thinkersbluff** [comment]
Awesome!

That is a huge help. Thank you!


I understand the TBD schedule.  I have the luxury of devoting all day every day to this project and I still don't know if/ when I will complete it.

I am very much in "learn a little/do a little" mode.

My biggest knowledge gap used to be python programming, but now it seems I need to dig a little deeper into repositories and workflow.

Best of luck with your projects!
