### ISSUE TITLE
Make error "multiple definitions of USARTx_IRQHandler"

### ISSUE THREAD

**Issue by reztierk** [Desuuuu/klipper#27]
Ran into this issue yesterday (and now have seen others posting about it on some facebook groups). Looks like there is conflict between the USARTx_IRQHandler function in `src/stm32/serial.c` and `src/stm32/serial_t5uid1.c` . I got around it by renaming the function and its usage in serial.c to USARTx_IRQHandler2 although I'm sure that isn't the correct solution.

![164622773_3463010913804515_5322665362240693107_o](https://user-images.githubusercontent.com/1424258/112230262-06b53580-8c0b-11eb-8396-48d251323a05.jpg)

**Comment by Desuuuu** [comment]
Solved as of commit 278b1c0.
