### ISSUE TITLE
Laser filament sensor support

### ISSUE THREAD

**Issue by ffnull** [Desuuuu/klipper#3]
Hello. Can you make support for this sensor?

https://duet3d.dozuki.com/Wiki/Duet3dFilamentMonitor_LaserVersion

**Comment by Desuuuu** [comment]
The only purpose of my fork is to add support for T5UID1 touchscreens.

Considering there's no connection between this and touchscreens, you're better off asking that question in the original Klipper repository.

If this is supported by the original Klipper, this is supported by this fork (or will be once the code is merged).
