### ISSUE TITLE
3/25/21 changes to lpc176x code breaks display

### ISSUE THREAD

**Issue by VIXIVIXIV** [Desuuuu/klipper#30]
I've been maintaining a fork of this fork that does automatic daily snapshots of the main klipper repo; there were some changes today that prevent the dgus display from initializing and functioning. Not sure why, no obvious reason from examining the changes, but reverting the changes from that day fixes it.

Ideally the dgus code would be made compatible with the upstream changes, as they identified some potential issues with the old code

**Comment by Desuuuu** [comment]
Sorry but this issue has nothing to do here. I don't have the will nor the time to constantly merge upstream changes, so I do it from time to time.

If you want to keep your fork up to date, that's your responsibility.
