### ISSUE TITLE
SAMPLE_RETRACT_DIST=<mm>

### ISSUE THREAD

**Issue by dragonisko** [Desuuuu/klipper#31]
SAMPLE_RETRACT_DIST=<mm> doesn't work, wont affect how high probe is rising after probing

**Comment by Desuuuu** [comment]
There's zero change in this fork related to this.

If this is an issue upstream and it has been fixed already, it will be fixed here once I merge the changes. If it hasn't been solved yet, please discuss the issue in the upstream repository.
