### ISSUE TITLE
Reverting to stock display firmware?

### ISSUE THREAD

**Issue by Bluetopia** [Desuuuu/klipper#33]
First of all, thanks for putting this together.  One of the biggest hangups I had with Klipper is the lack of machine control, and your updates helped get my touchscreen working with it. 

However, I've had to revert my recent changes to my printer (Ender 5 Plus with Silent board) as I wasn't getting the same quality as I was with stock hotend/silent board firmware and I needed to print some items. 

As part of this I wanted to revert the touch screen display changes as well.  I have tried clearing out the MicroSD card and copying the DWIN_SET files from the most recent Creality Silent board firmware release.  I get the proper main screen image, but none of the buttons are responsive, and there are no temperatures displayed.

![IMG_20210405_144016__01](https://user-images.githubusercontent.com/24968231/113611772-fba3d180-961c-11eb-9c99-fe03e3882be8.jpg)

Any thoughts on what I might need to do to revert the display update and getting it functional again?  Would including the optional T5UID1.cfg file from the wiki (https://github.com/Desuuuu/DGUS-reloaded-Klipper/wiki/Flashing-the-firmware) help here, or is that specific to your updates?  (It's binary, so I'm not certain what it actually does)

Thank you!

**Comment by Desuuuu** [comment]
Flash the `T5UID1.CFG` file available [here](https://github.com/Desuuuu/DGUS-reloaded-klipper/tree/master/extras/flash_reset), then  flash your new firmware and it should work properly.

This problem happens when the `13_*.bin` file has a different name across firmwares I think.

**Comment by Bluetopia** [comment]
No luck.  Tried flashing just the reset T5UID1.CFG file you linked to, then the display firmware from Creality without success.  Also tried replacing the Creality T5UID1.CFG file with the reset and flashing that (as I had done for the Klipper update originally) and no luck.  Display is still unresponsive and no temperature information is displayed.

You mention this potentially being an issue due to mismatched names.  I notice that the firmware files provided by Creality have a mismatched 13*.bin and 14*.bin file.  (Filename is in Chinese rather than English).  Would it be as simple as renaming these files to match the BMP, or are there references to the Chinese filename elsewhere that would prevent this from working?

**Comment by Desuuuu** [comment]
Yes, renaming the files to `13_touch.bin` and `14_variable.bin` should solve the problem. The prefix is what really matters, except for this bug obviously.

I'm surprised it didn't work using the reset config though. You did get a message about erasing the flash on the blue flashing screen, right?

**Comment by Bluetopia** [comment]
Yep, got "Formatting NAND Flash" displayed on the screen when using your cfg file.

Third time's the charm.  Renamed the Chinese files to match their English names, dropped your cfg file on the drive to ensure I'm working from a clean NAND and flashed.  Screen shows loading bar on startup, the temperatures are visible and the touch screen is responsive. 

Thanks for the help!
