### ISSUE TITLE
Section 't5uid1' is not a valid config section...

### ISSUE THREAD

**Issue by jasonturcotte** [Desuuuu/klipper#36]
Had the display running with Octoprint front-end and decided to try Fluidd.

When I copied my config to Fluidd, I get the error

`Section 't5uid1' is not a valid config section
Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted`

Once I comment that out, the printer talks to Fluidd, but I (obviously) do not have a working screen.

**Comment by Desuuuu** [comment]
This error most likely means you are not running my fork.

**Comment by jasonturcotte** [comment]
Forgive my ignorance, but does your fork run on the board of the printer (Ender 5) or the Raspberry Pi?

**Comment by Desuuuu** [comment]
Both the microcontroller and the host firmware contain modifications.
