### ISSUE TITLE
Make Warnings:

### ISSUE THREAD

**Issue by chappy1978** [Desuuuu/klipper#5]
I did a make and got a couple of Warnings from the build.
 Build Kconfig config file
#
# configuration written to /home/pi/klipper/.config
#
  Creating symbolic link out/board
  Compiling out/src/sched.o
  Compiling out/src/command.o
  Compiling out/src/basecmd.o
  Compiling out/src/debugcmds.o
  Compiling out/src/initial_pins.o
  Compiling out/src/gpiocmds.o
  Compiling out/src/stepper.o
  Compiling out/src/endstop.o
  Compiling out/src/adccmds.o
  Compiling out/src/spicmds.o
  Compiling out/src/thermocouple.o
  Compiling out/src/i2ccmds.o
  Compiling out/src/pwmcmds.o
  Compiling out/src/lcd_st7920.o
  Compiling out/src/lcd_hd44780.o
  Compiling out/src/buttons.o
  Compiling out/src/tmcuart.o
  Compiling out/src/spi_software.o
  Compiling out/src/neopixel.o
  Compiling out/src/sensor_adxl345.o
  Compiling out/src/avr/main.o
  Compiling out/src/avr/timer.o
  Compiling out/src/avr/gpio.o
  Compiling out/src/avr/adc.o
  Compiling out/src/avr/spi.o
  Compiling out/src/avr/i2c.o
  Compiling out/src/avr/hard_pwm.o
  Compiling out/src/avr/watchdog.o
  Compiling out/src/avr/serial.o
  Compiling out/src/generic/serial_irq.o
  Compiling out/src/avr/serial_t5uid1.o
  Compiling out/src/generic/t5uid1_irq.o
src/generic/t5uid1_irq.c: In function ‘t5uid1_timeout_event’:
src/generic/t5uid1_irq.c:90:49: warning: integer overflow in expression [-Woverflow]
     t->timer.waketime += timer_from_us(TIMER_MS * 1000);
                                                 ^
src/generic/t5uid1_irq.c: In function ‘reset_timer’:
src/generic/t5uid1_irq.c:102:58: warning: integer overflow in expression [-Woverflow]
         t->timer.waketime = now + timer_from_us(TIMER_MS * 1000);
                                                          ^
  Building out/compile_time_request.o
Version: 7b7b44b9-20201231_030251-octopi
  Linking out/klipper.elf
  Creating hex file out/klipper.elf.hex

**Comment by Desuuuu** [comment]
Thanks for the report!
