### ISSUE TITLE
Cannot use with SKR2 mainboard.  Error "pin PA2 is reserved for t5uid1"

### ISSUE THREAD

**Issue by phoenixfire425** [Desuuuu/klipper#64]
Cannot use with SKR2 mainboard.  Error "pin PA2 is reserved for t5uid1"

PA2 is used for TH0 on this board.

Is there a way to change the default pin??

https://cdn-3d.niceshops.com/upload/file/BIGTREETECH_SKR_2_user_manual.pdf

**Comment by Desuuuu** [comment]
You need to select the interface the touchscreen is connected to when configuring the firmware (enable advanced options if you don't see it).
